name: ${project.artifactId}
main: ${project.groupId}.thehelper.TheHelper
version: ${project.version}
website: ${project.url}
description: Helper plugin for Minecraft Middle Earth.
commands:
  helper:
    description: Helps new players
    usage: |
           /helper add <key> <value>
           /helper remove <key>
           /helper <help command>
permissions:
    thehelper.admin:
        description: Gives access to all helper commands
        default: op